version: '2.4'

x-brightsky:
  &brightsky
  image: jdemaeyer/brightsky:${BRIGHTSKY_IMAGE_TAG:-latest}
  depends_on:
    - postgres
    - redis
  environment:
    - BRIGHTSKY_DATABASE_URL=postgres://postgres:pgpass@postgres
    - BRIGHTSKY_REDIS_URL=redis://redis
  env_file: brightsky.env
  volumes:
    - .data/brightsky:/app/.cache

services:
  postgres:
    image: postgres:16-alpine
    shm_size: 512mb
    environment:
      POSTGRES_PASSWORD: pgpass
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:5-alpine
    restart: always
  worker:
    <<: *brightsky
    command: --migrate work
    restart: always
  web:
    <<: *brightsky
    command: serve --bind 0.0.0.0:5000
    restart: always
  brightsky:
    <<: *brightsky
    scale: 0
