{
 "title": "Bright Sky",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service:",
    "query": "label_values(traefik_service_requests_total, service)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_sum{code=\"200\", service=\"$service\"}[$__range])) / sum(increase(traefik_service_request_duration_seconds_count{code=\"200\", service=\"$service\"}[$__range])) * 1000"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_sum{code=\"200\", service=\"$service\"}[$interval])) / sum(increase(traefik_service_request_duration_seconds_count{code=\"200\", service=\"$service\"}[$interval])) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (code) (increase(traefik_service_requests_total{service=\"$service\"}[$interval])))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (le) (increase(traefik_service_request_duration_seconds_bucket{code=\"200\", service=\"$service\", le!=\"+Inf\"}[$__range])))",
     "legendFormat": "< {{le}} s"
    }
   ]
  }
 ]
}